name: Build and Push to Docker Hub and Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          # Etiqueta 'latest' para siempre tener la versión más reciente
          ${{ secrets.DOCKERHUB_USERNAME }}/authpython:latest
          # Etiqueta con el hash del commit para tener una referencia única por cada versión
          ${{ secrets.DOCKERHUB_USERNAME }}/authpython:${{ github.sha }}
    
    - name: Trigger EC2 Update
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Detener y eliminar el contenedor anterior si existe
          docker stop authpython || true
          docker rm authpython || true
          
          # Extraer la última imagen de Docker Hub
          # Usamos la etiqueta 'latest' para siempre obtener la versión más reciente
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/authpython:latest
          
          # Ejecutar el nuevo contenedor
          # Mapeamos el puerto 80 del host al puerto 5000 del contenedor
          # para que la aplicación sea accesible a través de HTTP estándar
          docker run -d --name authpython -p 80:5000 \
            -e PORT=5000 \
            --restart always \
            ${{ secrets.DOCKERHUB_USERNAME }}/authpython:latest
