name: Build and Push to Docker Hub and Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:${{ github.sha }}
    
    - name: Trigger EC2 Update
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Detener y eliminar el contenedor anterior si existe
          docker stop flask-app || true
          docker rm flask-app || true
          
          # Extraer la última imagen de Docker Hub
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest
          
          # Ejecutar el nuevo contenedor
          docker run -d --name flask-app -p 80:5000 \
            -e PORT=5000 \
            ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest
